import React, { useState, useEffect } from 'react';
import { SafeAreaProvider, useSafeAreaInsets } from 'react-native-safe-area-context';
// Wrap your outermost <Home> or root container inside <SafeAreaProvider>...</SafeAreaProvider>
import { View, ScrollView, Text, Pressable, StyleSheet, ActivityIndicator } from 'react-native';
import { Feather } from '@expo/vector-icons'; // Ensure your icon packs are imported cleanly
import { db } from '../config/firebaseConfig'; // Ensure path aligns with your directory mappings
import { collection, query, where, orderBy, onSnapshot } from 'firebase/firestore';



// 📱 ✅ LOCAL FIX: Embeds the missing ScreenHeader component into this sandbox context
function ScreenHeader({
  title,
  subtitle,
  onBack,
  right,
}: {
  title: string;
  subtitle?: string;
  onBack?: () => void;
  right?: React.ReactNode;
}) {
  const safeInsets = useSafeAreaInsets();
  const insets = safeInsets || { top: 0, bottom: 0, left: 0, right: 0 };

  return (
    <View style={[headerStyles.headerContainer, { paddingTop: Math.max(insets.top, 16) }]}>
      <View style={headerStyles.headerRow}>
        {onBack && (
          <Pressable onPress={onBack} style={headerStyles.headerBackButton} hitSlop={12}>
            <Feather name="arrow-left" size={20} color="#ffffff" />
          </Pressable>
        )}

        <View style={headerStyles.headerTitleContent}>
          <Text style={headerStyles.headerTitleText}>{title}</Text>
          {subtitle && <Text style={headerStyles.headerSubtitleText}>{subtitle}</Text>}
        </View>

        {right && <View style={headerStyles.headerRightSlot}>{right}</View>}
      </View>
    </View>
  );
}


function ActionsScreen({ onBack }: { onBack: () => void }) {
  const userId = "Admin_ForgetMeNotAI";

  // 🌟 STATE HOKS MANAGEMENT
  const [actions, setActions] = useState<any[]>([]);
  const [done, setDone] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);

  // ==========================================
  // 🧭 REAL-TIME LIVE LISTENING TASK STREAM
  // ==========================================
  useEffect(() => {
    console.log("🔮 Opening actions socket to fetch blueprints from Firestore...");

    // Tracks documents flagged as your active workspace view loops
    const q = query(
      collection(db, "analyses"),
      where("user_id", "==", userId),
      where("status", "==", "active_obsession"),
      orderBy("created_at", "desc")
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const liveActionsList: any[] = [];

      snapshot.forEach((docSnapshot) => {
        const data = docSnapshot.data();

        // Match system color variables accents dynamically using database tag entries
        const rawTag = (data.tag || "THINGS").toUpperCase();
        let computedColor = customAccents.cyan; // Fallback theme accent
        let computedIcon = "package";

        if (rawTag === 'PEOPLE' || rawTag === 'PERSONAL') {
          computedColor = customAccents.pink;
          computedIcon = "heart";
        } else if (rawTag === 'PLACES' || rawTag === 'TRAVEL') {
          computedColor = customAccents.gold;
          computedIcon = "sunrise";
        }

        // Extract instructions safely handling cross-nested fallback schemas
        const taskBlueprint =
          data.analysis?.preventiveAction ||
          data.gemini_signal_read?.preventive_action_blueprint ||
          data.mitigation ||
          "Verify physical checkpoints manually.";

        const operationalSummary =
          data.title ||
          data.analysis?.signal ||
          "Active Tracking Parameters";

        liveActionsList.push({
          id: docSnapshot.id,
          title: taskBlueprint,       // 🧠 The task is the core action script generated by Gemini
          detail: operationalSummary, // Subtitle points back to the mapped anomaly loop signature name
          color: computedColor,
          icon: computedIcon
        });
      });

      console.log(`📊 ACTIONS PIPELINE: Synced ${liveActionsList.length} dynamic checkpoints from cloud cluster.`);
      setActions(liveActionsList);
      setLoading(false);
    }, (error) => {
      console.error("💥 Error streaming real-time diagnostic actions matrix:", error);
      setLoading(false);
    });

    return () => unsubscribe();
  }, [userId]);

  // Compute percentages safely avoiding division-by-zero crashes if DB list is currently empty
  const totalTasksCount = actions.length || 1;
  const tasksCompletedCount = done.filter(id => actions.some(a => a.id === id)).length;
  const progressPercentage = Math.round((tasksCompletedCount / actions.length) * 100) || 0;

  if (loading) {
    return (
      <View style={[styles.screen, { justifyContent: 'center', alignItems: 'center' }]}>
        <ActivityIndicator size="large" color="#00ffcc" />
        <Text style={{ color: '#8a8f98', marginTop: 12, fontSize: 13 }}>Hydrating task footprints...</Text>
      </View>
    );
  }

  return (
    <View style={styles.screen}>
      <ScreenHeader title="Prevent the omission" subtitle="Tiny actions. Better future-you." onBack={onBack} />

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.innerScroll}>
        <View style={styles.actionsIntro}>
          <Text style={styles.actionsKicker}>THE LAST MILE</Text>
          <Text style={styles.actionsTitle}>Make the invisible{"\n"}easy to handle.</Text>
          <Text style={styles.actionsCopy}>A prediction only helps when it becomes a small, kind action.</Text>
        </View>

        {actions.length === 0 ? (
          <View style={{ padding: 24, alignItems: 'center', opacity: 0.6 }}>
            <Text style={{ color: '#fff', fontSize: 14 }}>No actions pending. Create a signal on your capture screen.</Text>
          </View>
        ) : (
          actions.map((action) => {
            const completed = done.includes(action.id);
            return (
              <Pressable
                key={action.id}
                onPress={() => {
                  if (typeof tap === 'function') tap();
                  setDone((current) =>
                    completed ? current.filter((id) => id !== action.id) : [...current, action.id]
                  );
                }}
                style={[styles.actionRow, completed && styles.actionRowDone]}
              >
                <View style={[styles.actionIcon, { backgroundColor: `${action.color}18` }]}>
                  <Feather name={action.icon as any} size={20} color={action.color} />
                </View>
                <View style={styles.actionCopy}>
                  {/* Displays your high-fidelity preventive action string block text */}
                  <Text style={[styles.actionTitle, completed && styles.actionTitleDone]}>{action.title}</Text>
                  <Text style={styles.actionDetail}>{action.detail}</Text>
                </View>
                <View style={[styles.actionCheck, completed && styles.actionCheckDone]}>
                  {completed ? (
                    <Feather name="check" size={15} color={theme.background} />
                  ) : (
                    <Feather name="plus" size={16} color={theme.mutedForeground} />
                  )}
                </View>
              </Pressable>
            );
          })
        )}

        {/* --- DYNAMIC METRICS SUMMARY TRACK CARD --- */}
        <View style={styles.donePanel}>
          <View style={styles.donePanelTop}>
            <Text style={styles.donePanelTitle}>{tasksCompletedCount}/{actions.length} made visible</Text>
            <Text style={styles.donePanelPercent}>{progressPercentage}%</Text>
          </View>
          <View style={styles.progressTrack}>
            <View style={[styles.progressFill, { width: `${progressPercentage}%` }]} />
          </View>
          <Text style={styles.donePanelCopy}>
            {tasksCompletedCount === actions.length && actions.length > 0
              ? 'Nothing hiding today. Nice work.'
              : 'No pressure. One small action is enough to change the shape of a day.'}
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

// ✅ Ensure these theme definitions are present at the bottom of your file
export const customAccents = {
  pink: '#ff007f',    // Bright cyber pink for PEOPLE tasks
  gold: '#ffd700',    // Glowing gold for PLACES logistics
  cyan: '#00ffcc',    // Neon cyan for THINGS / PRACTICAL checkpoints
};

export const theme = {
  background: '#121214',
  mutedForeground: '#8a8f98',
};

// Layout weights for the header component
const headerStyles = StyleSheet.create({
  headerContainer: {
    backgroundColor: '#050506',
    borderBottomWidth: 1,
    borderColor: '#1c1c1f',
    paddingBottom: 16,
    paddingHorizontal: 20,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerBackButton: {
    marginRight: 16,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#121214',
    borderRadius: 8,
  },
  headerTitleContent: {
    flex: 1,
  },
  headerTitleText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '800',
  },
  headerSubtitleText: {
    color: '#8a8f98',
    fontSize: 12,
    marginTop: 2,
  },
  headerRightSlot: {
    marginLeft: 12,
  }
});


// 🎨 ✅ THE DIRECT FIX: Add the missing styles object inside this file
const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#050506', // Deep cyber canvas backdrop matching layout themes
  },
  innerScroll: {
    padding: 20,
    paddingBottom: 40,
  },
  actionsIntro: {
    marginBottom: 24,
    marginTop: 10,
  },
  actionsKicker: {
    color: '#00ffcc',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 2,
    marginBottom: 8,
  },
  actionsTitle: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 36,
    marginBottom: 12,
  },
  actionsCopy: {
    color: '#8a8f98',
    fontSize: 14,
    lineHeight: 20,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#121214',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#1c1c1f',
  },
  actionRowDone: {
    opacity: 0.6,
    borderColor: '#121214',
    backgroundColor: '#0c0c0e',
  },
  actionIcon: {
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  actionCopy: {
    flex: 1,
    marginRight: 12,
  },
  actionTitle: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
    marginBottom: 4,
  },
  actionTitleDone: {
    textDecorationLine: 'line-through',
    color: '#8a8f98',
  },
  actionDetail: {
    color: '#62626a',
    fontSize: 12,
    fontWeight: '500',
  },
  actionCheck: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#2c2c30',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionCheckDone: {
    backgroundColor: '#ffffff',
    borderColor: '#ffffff',
  },
  donePanel: {
    backgroundColor: '#0c0c0e',
    borderRadius: 12,
    padding: 20,
    marginTop: 16,
    borderWidth: 1,
    borderColor: '#141417',
  },
  donePanelTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  donePanelTitle: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  donePanelPercent: {
    color: '#00ffcc',
    fontSize: 16,
    fontWeight: '900',
  },
  progressTrack: {
    height: 6,
    backgroundColor: '#1c1c1f',
    borderRadius: 3,
    marginBottom: 14,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#00ffcc',
    borderRadius: 3,
  },
  donePanelCopy: {
    color: '#62626a',
    fontSize: 13,
    lineHeight: 18,
  },
});

export default ActionsScreen;

