import { StyleSheet, Dimensions } from 'react-native';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

export const artStyles = StyleSheet.create({
  cardContainer: {
    width: '100%',
    backgroundColor: '#111113',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#1E1E22',
    padding: 16,
    marginVertical: 12,
  },
  splitLayoutRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    gap: 16,
  },

  // --- Left Half: Core Tracker ---
  trackerSideColumn: {
    flex: 1.1,
    justifyContent: 'space-between',
  },
  brandGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  eyebrowText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#00f0ff',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginLeft: 6,
  },
  canvasArcTrack: {
    width: '100%',
    height: 12,
    position: 'relative',
    justifyContent: 'center',
    marginBottom: 16,
  },
  baseLine: {
    width: '100%',
    height: 2,
    backgroundColor: '#1C1C21',
    borderRadius: 1,
  },
  glowProgressLine: {
    position: 'absolute',
    left: 0,
    height: 2,
    backgroundColor: '#ff007f',
  },
  pulseThumb: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#ff007f',
    top: 2,
  },
  momentumTag: {
    position: 'absolute',
    right: 0,
    top: -12,
    fontSize: 9,
    fontWeight: '700',
    color: '#ff007f',
  },
  phraseRowGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  dynamicAvatarBadge: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#1A1A1E',
    borderWidth: 1,
    borderColor: '#26262B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  coreIntentPhrase: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    lineHeight: 20,
  },

  // 🧭 Concentric Arc Layer Spacing
  miniConcentricTrack: {
    width: 34,
    height: 34,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  outerArcGlow: {
    position: 'absolute',
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 2.5,
    borderColor: '#ff007f',
    borderBottomColor: 'transparent',
    borderLeftColor: 'transparent',
    transform: [{ rotate: '-45deg' }],
  },
  innerArcGlow: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#ffbf00',
    borderTopColor: 'transparent',
    transform: [{ rotate: '30deg' }],
  },

  signalPillRow: {
    flexDirection: 'column',
    gap: 4,
  },
  missingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 191, 0, 0.04)',
    borderColor: 'rgba(255, 191, 0, 0.12)',
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    alignSelf: 'flex-start',
  },
  pillLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#ffbf00',
    marginLeft: 4,
  },

  // --- Right Half: Layout Controls ---
  conceptSideColumn: {
    flex: 0.9,
    backgroundColor: '#151518',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#222226',
    padding: 12,
    justifyContent: 'space-between',
  },
  conceptMetaHeader: {
    fontSize: 10,
    fontWeight: '700',
    color: '#71717A',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  conceptDescription: {
    fontSize: 11,
    color: '#A1A1AA',
    lineHeight: 15,
    marginBottom: 8,
  },

  // Dynamic Scatter Grid Fixes
  graphicVectorBox: {
    width: '100%',
    height: 46,
    backgroundColor: '#0F0F11',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#1C1C21',
    position: 'relative',
    overflow: 'hidden',
  },
  chartGridLine: {
    position: 'absolute',
    width: 1,
    height: '100%',
    backgroundColor: 'rgba(113, 113, 122, 0.08)',
  },
  networkLinkLine: {
    position: 'absolute',
    height: 1,
    backgroundColor: 'rgba(255, 0, 127, 0.25)',
  },
  scatterNodeCircle: {
    position: 'absolute',
    width: 6,
    height: 6,
    borderRadius: 3,
  },

  footerActionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: '#1E1E22',
    paddingTop: 12,
    marginTop: 14,
  },
  windowMetaText: {
    fontSize: 12,
    color: '#71717A',
  },
  boldHighlight: {
    color: '#ffbf00',
    fontWeight: '600',
  },
  anchorButtonSquareOnly: {
    width: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: 'rgba(57, 255, 20, 0.1)',
    borderColor: '#39FF14',
    borderWidth: 1.2,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Modal Drawer Layout Configuration
  backdropOverlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 5, 6, 0.85)',
    justifyContent: 'flex-end',
  },
  dismissArea: {
    flex: 1,
  },
  sheetContainer: {
    width: '100%',
    maxHeight: SCREEN_HEIGHT * 0.75,
    backgroundColor: '#111113',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderColor: '#222226',
    borderBottomWidth: 0,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  dragHandleBar: {
    width: 32,
    height: 3,
    backgroundColor: '#2E2E33',
    borderRadius: 1.5,
    alignSelf: 'center',
    marginBottom: 20,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  sheetSubtitle: {
    fontSize: 10,
    fontWeight: '700',
    color: '#00f0ff',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 16,
  },
  scrollContent: {
    width: '100%',
    marginBottom: 16,
  },
  techSection: {
    backgroundColor: '#16161A',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#222226',
    padding: 14,
    marginBottom: 10,
  },
  techRowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  techTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  techDesc: {
    fontSize: 12,
    color: '#71717A',
    lineHeight: 16,
  },
  closeSheetButton: {
    width: '100%',
    backgroundColor: '#1C1C21',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#26262B',
  },
  closeButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#A1A1AA',
  },
});
