import React, { useState, useEffect } from 'react';
import { View, Text, ScrollView, Image, ActivityIndicator, Pressable, StyleSheet, Dimensions, Platform } from 'react-native';
import { Feather } from '@expo/vector-icons';

// FIREBASE CLOUD INFRASTRUCTURE IMPORTS
import { db } from '../config/firebaseConfig';
import { collection, query, where, orderBy, onSnapshot } from 'firebase/firestore';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

// APPMINIMALIST HIGH-CONTRAST TOKENS
const theme = { cyan: '#00f0ff', background: '#050506' };
const customAccents = { pink: '#ff007f', gold: '#ffbf00', cyan: '#00f0ff' };

interface CapturedItem {
  id: string;
  title: string;
  detail: string;
  tag: string;
  color: string;
}

interface MemoryScreenProps {
  onBack: () => void;
  captured: CapturedItem[];
}

// --- SUBCOMPONENT HEADER ELEMENTS LAYOUT ---
function ScreenHeader({ title, subtitle, onBack }: { title: string; subtitle: string; onBack: () => void }) {
  return (
    <View style={styles.headerRow}>
      <Pressable onPress={onBack} style={styles.backButton}>
        <Feather name="arrow-left" size={16} color="#FFFFFF" />
      </Pressable>
      <View style={styles.headerTextContainer}>
        <Text style={styles.headerTitle}>{title}</Text>
        <Text style={styles.headerSubtitle}>{subtitle}</Text>
      </View>
    </View>
  );
}

function SectionTitle({ eyebrow, title, action }: { eyebrow: string; title: string; action: string }) {
  return (
    <View style={styles.sectionTitleRow}>
      <View>
        <Text style={styles.sectionEyebrow}>{eyebrow}</Text>
        <Text style={styles.sectionMainTitle}>{title}</Text>
      </View>
      <View style={styles.sectionActionBadge}>
        <Text style={styles.sectionActionText}>{action}</Text>
      </View>
    </View>
  );
}

function Pill({ label, color }: { label: string; color: string }) {
  return (
    <View style={[styles.pillContainer, { borderColor: color, backgroundColor: `${color}15` }]}>
      <Text style={[styles.pillText, { color: color }]}>{label}</Text>
    </View>
  );
}

function FGlobe({ size }: { size: number }) {
  return (
    <View style={[styles.globeFrame, { width: size, height: size, borderRadius: size / 2 }]}>
      <Feather name="globe" size={size * 0.5} color="#00f0ff" />
    </View>
  );
}

// =========================================================================
// 🛡️ DYNAMIC MEMORY ENGINE CONTAINER - WITH FIREBASE REAL-TIME SYNC
// =========================================================================
export function MemoryScreen({ onBack, captured = [] }: MemoryScreenProps) {
  const userId = "Admin_ForgetMeNotAI";
  const [dbSignals, setDbSignals] = useState<CapturedItem[]>([]);
  const [loading, setLoading] = useState(true);

  // 🌟 FILTER TAB STATE MANAGER: Keeps track of 'All', 'People', 'Places', 'Things'
  const [activeTab, setActiveTab] = useState<'All' | 'People' | 'Places' | 'Things'>('All');

  useEffect(() => {
    console.log("🔮 Opening data pipeline socket to read user signals from Firestore...");

    const q = query(
      collection(db, "analyses"),
      where("user_id", "==", userId),
      orderBy("created_at", "desc")
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const liveRecords: CapturedItem[] = [];

      snapshot.forEach((doc) => {
        const data = doc.data();
     // 🌟 EXTRACT CATEGORY TAG FROM ROOT DATA PREFERENCES:
        const computedTag = (data.tag || data.nodes?.[0] || "THINGS").toUpperCase();

        // Remap alternative title keys to catch exact database schemas
        if (computedTag === 'PERSONAL') computedTag = 'PEOPLE';
        if (computedTag === 'TRAVEL') computedTag = 'PLACES';
        if (computedTag === 'OBJECT') computedTag = 'THINGS';

        let computedColor = customAccents.cyan;
        if (computedTag === 'PEOPLE') computedColor = customAccents.pink;
        else if (computedTag === 'PLACES') computedColor = customAccents.gold;

        liveRecords.push({
          id: doc.id,
          // 🌟 THE CRITICAL DYNAMIC DATA LOOKUP FIX:
          // Reads the exact fields generated by Gemini inside your capture screen function!
          title: data.title || data.signal || `Review ${data.omission_item} Map`,
          detail: data.detail || data.mitigation || "Active tracking parameters active.",
          tag: computedTag,
          color: computedColor
        });
      });

      setDbSignals(liveRecords);
      setLoading(false);
    }, (error) => {
      console.error("💥 Error streaming real database signals:", error);
      setLoading(false);
    });

    return () => unsubscribe();
  }, [userId]);

  // Consolidate cloud and local records arrays
  const combinedSignalsMap = [...dbSignals];

  // Clean matching duplicates
  const uniqueSignals = combinedSignalsMap.filter(
    (item, index, self) => index === self.findIndex((t) => t.id === item.id)
  );

  // 🌟 THE DYNAMIC FILTER TRIGGER: Computes lists based on the active selection tab
  const filteredSignals = uniqueSignals.filter((item) => {
    if (activeTab === 'All') return true;
    return item.tag.toUpperCase() === activeTab.toUpperCase();
  });

  return (
    <View style={styles.screen}>
      <ScreenHeader title="Signal map" subtitle="Everything you’ve let me notice" onBack={onBack} />

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.innerScroll}>

        {/* --- HERO COUNTER DISPLAY --- */}
        <View style={styles.memoryHero}>
          <Image source={require('@/assets/images/memory-orb.jpg')} style={styles.memoryImage} />
          <View style={styles.memoryOverlay} />
          <View style={styles.memoryHeroCopy}>
            {/* Real-time calculated overall data length counter */}
            <Text style={styles.memoryScore}>{uniqueSignals.length}</Text>
            <Text style={styles.memoryScoreLabel}>signals in your orbit</Text>
          </View>
          <View style={styles.memoryGlobe}>
            <FGlobe size={58} />
          </View>
        </View>

        {/* --- INTERACTIVE TAB SELECTION ROW LAYOUT --- */}
        <View style={styles.memoryTabs}>
          {(['All', 'People', 'Places', 'Things'] as const).map((tabName) => (
            <Pressable key={tabName} onPress={() => setActiveTab(tabName)}>
              <Text style={[
                styles.memoryTab,
                activeTab === tabName && styles.memoryTabActive
              ]}>
                {tabName === 'All' ? 'All signals' : tabName}
              </Text>
            </Pressable>
          ))}
        </View>

        {/* --- CORE SIGNALS MAP ITERATOR LIST --- */}
        <SectionTitle eyebrow="JUST NOW" title={`${activeTab} context`} action="Capture" />

        {loading ? (
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="small" color={theme.cyan} />
            <Text style={styles.loadingText}>Streaming Live Data...</Text>
          </View>
        ) : filteredSignals.length === 0 ? (
          <View style={styles.emptyContainer}>
            <Feather name="folder" size={24} color="#71717A" />
            <Text style={styles.emptyText}>No active {activeTab.toLowerCase()} signals tracked.</Text>
          </View>
        ) : (
          filteredSignals.map((item) => (
            <View key={item.id} style={styles.memoryRow}>
              <View style={[styles.memoryDot, { backgroundColor: item.color }]} />
              <View style={styles.memoryCopy}>
                <Text style={styles.memoryTitle}>{item.title}</Text>
                <Text style={styles.memoryDetail}>{item.detail}</Text>
              </View>
              <Pill label={item.tag} color={item.color} />
            </View>
          ))
        )}

        {/* --- POLICY FOOTER --- */}
        <View style={styles.memoryNotice}>
          <Feather name="lock" size={17} color={theme.cyan} />
          <Text style={styles.memoryNoticeText}>Your signal map belongs to you. ForgetMeNot doesn’t sell or share your context.</Text>
        </View>

      </ScrollView>
    </View>
  );
}

// =========================================================================
// 🎨 CYBER-DARK MINIMALIST DESIGN LAYOUT TOKENS STYLE CODES
// =========================================================================
const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#050506',
    paddingTop: Platform.OS === 'ios' ? 44 : 12
  },
  innerScroll: {
    padding: 16
  },

  // Header section layout configurations
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginVertical: 14,
    gap: 14
  },
  backButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#111113',
    borderWidth: 1,
    borderColor: '#1E1E22',
    alignItems: 'center',
    justifyContent: 'center'
  },
  headerTextContainer: {
    flex: 1
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF'
  },
  headerSubtitle: {
    fontSize: 11,
    color: '#71717A',
    marginTop: 1
  },

  // Hero Card layout tokens
  memoryHero: {
    width: '100%',
    height: 160,
    borderRadius: 14,
    backgroundColor: '#111113',
    overflow: 'hidden',
    position: 'relative',
    marginVertical: 12,
    borderWidth: 1,
    borderColor: '#1E1E22'
  },
  memoryImage: {
    width: '100%',
    height: '100%',
    opacity: 0.25
  },
  memoryOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(5,5,6,0.3)'
  },
  memoryHeroCopy: {
    position: 'absolute',
    left: 20,
    bottom: 20
  },
  memoryScore: {
    fontSize: 36,
    fontWeight: '900',
    color: '#00f0ff'
  },
  memoryScoreLabel: {
    fontSize: 12,
    color: '#A1A1AA',
    fontWeight: '600',
    marginTop: 2
  },
  memoryGlobe: {
    position: 'absolute',
    right: 20,
    bottom: 20
  },
  globeFrame: {
    backgroundColor: 'rgba(0,240,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(0,240,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center'
  },

  // Navigation tab bar triggers layout tokens
  memoryTabs: {
    flexDirection: 'row',
    gap: 14,
    marginVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#1E1E22',
    paddingBottom: 10
  },
  memoryTabActive: {
    fontSize: 13,
    fontWeight: '700',
    color: '#00f0ff',
    borderBottomWidth: 2,
    borderBottomColor: '#00f0ff',
    paddingBottom: 8
  },
  memoryTab: {
    fontSize: 13,
    fontWeight: '600',
    color: '#71717A'
  },

  // Section titles row layout
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 14,
    marginBottom: 12
  },
  sectionEyebrow: {
    fontSize: 9,
    fontWeight: '700',
    color: '#A855F7',
    letterSpacing: 1
  },
  sectionMainTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
    marginTop: 2
  },
  sectionActionBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: 'rgba(57,255,20,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(57,255,20,0.15)'
  },
  sectionActionText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#39FF14',
    textTransform: 'uppercase'
  },

  // List Rows Item layout tokens
  memoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111113',
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#1E1E22',
    gap: 12
  },
  memoryDot: {
    width: 8,
    height: 8,
    borderRadius: 4
  },
  memoryCopy: {
    flex: 1
  },
  memoryTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF'
  },
  memoryDetail: {
    fontSize: 11,
    color: '#A1A1AA',
    marginTop: 2,
    lineHeight: 14
  },

  // Custom context status text badge pills
  pillContainer: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1
  },
  pillText: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5
  },

  // Live state loader activity indicators container
  loadingContainer: {
    paddingVertical: 44,
    alignItems: 'center',
    gap: 10
  },
  loadingText: {
    fontSize: 11,
    color: '#71717A'
  },

  // Lower privacy policy informational text banner
  memoryNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#16161A',
    borderWidth: 1,
    borderColor: '#222226',
    borderRadius: 8,
    padding: 12,
    marginTop: 20,
    gap: 10
  },
  memoryNoticeText: {
    flex: 1,
    fontSize: 11,
    color: '#71717A',
    lineHeight: 15
  }
}); // ✅ FIXED: Symmetrically closed the entire StyleSheet engine block here
